SELECT (SELECT COUNT(*) FROM Product ) "PRODUCTS",
       (SELECT COUNT(*) FROM Keyword ) "KEYWORDS",
       (SELECT COUNT(*) FROM Customer ) "CUSTOMERS",
       (SELECT COUNT(*) FROM Pbasket ) "PURCHASE BUSKETS",
       (SELECT COUNT(*) FROM PP ) "PURCHASE PRODUCTS",
       (SELECT COUNT(*) FROM Cevaluation ) "CUSTOMER EVALUATIONS"
FROM DUAL;

